---

# Include variables and define needed variables.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

# Setup/options.
- include_tasks: "Setup_Options.yml"

# Setup/install tasks.
- include_tasks: "Setup_{{ ansible_os_family }}.yml"

# Setup ipxe
# - include_tasks: "ipxe.yml"

# Setup syslinux-3.86
# - include_tasks: "syslinux386.yml"

# Setup OS ESXi
# - include_tasks: "os_esxi.yml"

# Setup OS Windows
# - include_tasks: "os_windows.yml"
