---

# Include variables and define needed variables.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

# Setup/options.
- include_tasks: "Setup_Options.yml"

# Setup/install tasks.
- include_tasks: "Setup_{{ ansible_os_family }}.yml"

- name: Check /srv/tftp
  stat:
    path: /srv/tftp
  register: path_srv_tftp

# Setup ipxe
- include_tasks: "ipxe.yml"
  when: path_srv_tftp.stat.exists
# Setup syslinux-3.86
- include_tasks: "syslinux386.yml"
  when: path_srv_tftp.stat.exists

# Setup OS ESXi
# - include_tasks: "os_esxi.yml"

# Setup OS Windows
# - include_tasks: "os_windows.yml"
