---

# RUBY/RAILS doesn't benefit from hugepages
- name: Disable thp
  ansible.builtin.shell: |
      echo never > /sys/kernel/mm/transparent_hugepage/enabled
      echo never > /sys/kernel/mm/transparent_hugepage/defrag
      echo 0 > /proc/sys/vm/compaction_proactiveness

- name: Install CA Certificates
  ansible.builtin.apt:
    name: ca-certificates

- name: Creating certs file in /usr/local/share/ca-certificates
  ansible.builtin.copy:
    dest: "{{ item.name }}"
    content: "{{ item.filecontent }}"
    owner: root
    group: root
    mode: 0644
  loop: "{{ vault_ca_certs_files }}"

- name: Update ca-certificates
  ansible.builtin.shell: |
    update-ca-certificates

- name: Install gpg
  ansible.builtin.apt:
    name: gpg

- name: "Install Git"
  ansible.builtin.apt:
    name: git

- name: Install Puppet Repository
  block:
    - name: Add Public Key
      ansible.builtin.apt_key:
        url: https://apt.puppetlabs.com/keyring.gpg
        state: present
    - name: Install Puppet Repo
      ansible.builtin.apt_repository:
        repo: deb https://apt.puppetlabs.com/ {{ ansible_distribution_release }} {{ puppet_version }}
        state: present
        filename: '{{ puppet_version }}'

- name: Install Foreman Repository
  block:
    - name: Add Public Key
      ansible.builtin.apt_key:
        url: https://deb.theforeman.org/foreman.asc
        state: present
    - name: Install Foreman Repo
      ansible.builtin.apt_repository:
        repo: deb https://deb.theforeman.org/ {{ ansible_distribution_release }} {{ foreman_version }}
        state: present
        filename: 'foreman'
    - name: Install Foreman Plugin Repo
      ansible.builtin.apt_repository:
        repo: deb https://deb.theforeman.org/ plugins {{ foreman_version }}
        state: present
        filename: 'foreman_plugins'

- name: Download Foreman installer package
  ansible.builtin.apt:
    name: foreman-installer
    update_cache: yes
    state: latest

- name: "Install Puppet Agent"
  ansible.builtin.apt:
    name: puppet-agent

- name: "Bootstap Puppet Agent ssl"
  ansible.builtin.shell: |
    /opt/puppetlabs/bin/puppet config set server {{ groups['tfm_puppet'][0] }} --section main
    /opt/puppetlabs/bin/puppet ssl bootstrap --server {{ groups['tfm_puppet'][0] }}

- name: "Install and Configure Puppet Root CA"
  block:
    - name: "Fetch Puppet Root CA"
      ansible.builtin.shell: |
        echo quit | openssl s_client -showcerts -servername server -connect {{ groups['tfm_puppet'][0] }}:8140 > /usr/local/share/ca-certificates/{{ groups['tfm_puppet'][0] }}-CA.crt 2>&1
      args:
        executable: /bin/bash
    - name: "Install Puppet Root CA"
      ansible.builtin.shell: |
        update-ca-certificates --fresh
      args:
        executable: /bin/bash

- name: Ensure group "puppet" exists
  ansible.builtin.group:
    name: puppet
    state: present

- name: Ensure group "foreman-proxy" exists
  ansible.builtin.group:
    name: foreman-proxy
    state: present

# Include plugins: salt
- include_tasks: "plugin_salt_pre.yml"
  when: plugin_salt | bool

# Setup discovery
# - include_tasks: "discovery.yml"
#   when: plugin_discovery | bool

- name: "Install and Configure Foreman PROXY"
  block:

    - name: "Install Foreman PROXY"
      vars:
        argv_start:
        - foreman-installer
        - --no-enable-foreman
        - --no-enable-puppet
        - --no-enable-foreman-plugin-puppet
        - --no-enable-foreman-cli-puppet
        - --enable-foreman-proxy
        - --puppet-group=root
        - --puppet-codedir="/etc/puppetlabs/code"
      ansible.builtin.shell: |
        {{ argv_start | join(' ') }} \
        {{ foreman_cmd_options | join(' ') }}
      args:
        executable: /bin/bash

    - name: Creating file /etc/puppetlabs/puppet/autosign.conf
      ansible.builtin.copy:
        dest: /etc/puppetlabs/puppet/autosign.conf
        content: |
          *.{{ inventory_hostname | replace(inventory_hostname_short + '.','') }}
        owner: root
        group: foreman-proxy
        mode: 0664

    # Include plugins: bind
    - include_tasks: "plugin_bind.yml"
      when: plugin_bind | bool

    # Setup monitoring
    - include_tasks: "monitoring.yml"
      when: plugin_monitoring | bool

    - name: Restart service foreman-proxy
      ansible.builtin.service:
        name: foreman-proxy
        state: restarted

# Include plugins: salt
- include_tasks: "plugin_salt_post.yml"
  when: plugin_salt | bool

- name: Creates directory /etc/ansible
  ansible.builtin.file:
    path: /etc/ansible
    state: directory
    owner: root
    group: foreman-proxy
    mode: 0750

- name: Creating empty file /etc/ansible/ansible.cfg
  ansible.builtin.copy:
    dest: /etc/ansible/ansible.cfg
    content: ""
    owner: root
    group: foreman-proxy
    mode: 0640

- name: "Bootstap Puppet Agent ssl"
  ansible.builtin.shell: |
    /opt/puppetlabs/bin/puppet config set server {{ groups['tfm_puppet'][0] }} --section main

- name: Restart service puppet
  ansible.builtin.service:
    name: puppet
    state: restarted
