---

- name: Disable thp
  ansible.builtin.shell: |
      echo never > /sys/kernel/mm/transparent_hugepage/enabled
      echo never > /sys/kernel/mm/transparent_hugepage/defrag
      echo 0 > /proc/sys/vm/compaction_proactiveness

# - name: "Update CA Certificates"
#   ansible.builtin.apt:
#     name: ca-certificates
#     update_cache: yes

- name: Install gpg
  apt:
    name: gpg
    update_cache: yes

- name: Install Puppet Repository
  block:
    - name: Add Public Key
      apt_key:
        url: https://apt.puppetlabs.com/keyring.gpg
        state: present
    - name: Install Puppet Repo
      apt_repository:
        repo: deb https://apt.puppetlabs.com/ {{ ansible_distribution_release }} {{ puppet_version }}
        state: present
        filename: /etc/apt/sources.list.d/{{ puppet_version }}.list

- name: Install Foreman Repository
  block:
    - name: Add Public Key
      apt_key:
        url: https://deb.theforeman.org/foreman.asc
        state: present
    - name: Install Foreman Repo
      apt_repository:
        repo: deb https://deb.theforeman.org/ {{ ansible_distribution_release }} {{ foreman_version }}
        state: present
        filename: /etc/apt/sources.list.d/foreman.list
    - name: Install Foreman Plugin Repo
      apt_repository:
        repo: deb https://deb.theforeman.org/ plugins {{ foreman_version }}
        state: present
        filename: /etc/apt/sources.list.d/foreman_plugins.list

- name: "Install Git"
  ansible.builtin.apt: 
    name: git 
    force: yes 
    allow_unauthenticated: true

- name: "Download Foreman installer package"
  ansible.builtin.apt:
    name: foreman-installer
    force: yes
    allow_unauthenticated: true

- name: "Install Puppet Agent"
  ansible.builtin.apt: 
    name: puppet-agent 
    force: yes 
    allow_unauthenticated: true
    
- name: "Bootstap Puppet Agent ssl"
  ansible.builtin.shell: |
    /opt/puppetlabs/bin/puppet config set server {{ groups['tfm_puppet'][0] }} --section main
    /opt/puppetlabs/bin/puppet ssl bootstrap --server {{ groups['tfm_puppet'][0] }}

- name: "Install and Configure Puppet Root CA"
  block:
    - name: "Fetch Puppet Root CA"
      ansible.builtin.shell: |
        echo quit | openssl s_client -showcerts -servername server -connect {{ groups['tfm_puppet'][0] }}:8140 > /usr/local/share/ca-certificates/{{ groups['tfm_puppet'][0] }}-CA.crt 2>&1
      args:
        executable: /bin/bash  
    - name: "Install Puppet Root CA"
      ansible.builtin.shell: |
        update-ca-certificates --fresh
      args:
        executable: /bin/bash  

- name: Ensure group "puppet" exists
  ansible.builtin.group:
    name: puppet
    state: present

- name: Ensure group "foreman-proxy" exists
  ansible.builtin.group:
    name: foreman-proxy
    state: present

# Include plugins: bind
- include_tasks: "bind.yml"

# Include plugins: salt
- include_tasks: "salt_pre.yml"
  when: _salt_test | bool

- name: "Install and Configure Foreman PROXY"
  block:

    - name: "Install Foreman PROXY"
      vars:
        argv_start:
        - foreman-installer
        - --no-enable-foreman
          - --no-enable-puppet
        - --no-enable-foreman-plugin-puppet 
        - --no-enable-foreman-cli-puppet
        - --enable-foreman-proxy
        - --puppet-group=root
        - --puppet-codedir="/etc/puppetlabs/code"
      ansible.builtin.shell: |
        {{ argv_start | join(' ') }} \
        {{ foreman_cmd_options | join(' ') }}
      args:
        executable: /bin/bash

    - name: SALT, Ensure permissive_pki_access is set
      ansible.builtin.lineinfile:
        path: /etc/salt/master.d/foreman.conf
        regexp: '^# permissive_pki_access'
        line: 'permissive_pki_access: True'
      when: _salt_test | bool

    # Include plugins: salt
    - include_tasks: "salt_post.yml"
      when: _salt_test | bool

    - name: Creating file /etc/puppetlabs/puppet/autosign.conf
      ansible.builtin.copy:
        dest: /etc/puppetlabs/puppet/autosign.conf
        content: |
          *.{{ inventory_hostname | replace(inventory_hostname_short + '.','') }}
        owner: root
        group: foreman-proxy
        mode: 0664

    - name: Restart service foreman-proxy
      ansible.builtin.service:
        name: foreman-proxy
        state: restarted

- name: Creates directory /etc/ansible
  ansible.builtin.file:
    path: /etc/ansible
    state: directory
    owner: root
    group: foreman-proxy
    mode: 0750

- name: Creating empty file /etc/ansible/ansible.cfg
  ansible.builtin.copy:
    dest: /etc/ansible/ansible.cfg
    content: ""
    owner: root
    group: foreman-proxy
    mode: 0640

- name: "Bootstap Puppet Agent ssl"
  ansible.builtin.shell: |
    /opt/puppetlabs/bin/puppet config set server {{ groups['tfm_puppet'][0] }} --section main

- name: Restart service puppet
  ansible.builtin.service:
    name: puppet
    state: restarted
