---

- name: Disable thp
  ansible.builtin.shell: |
      echo never > /sys/kernel/mm/transparent_hugepage/enabled
      echo never > /sys/kernel/mm/transparent_hugepage/defrag
      echo 0 > /proc/sys/vm/compaction_proactiveness

# - name: "Update CA Certificates"
#   ansible.builtin.apt:
#     name: ca-certificates
#     update_cache: yes

- name: Install Puppet Repository
  block:
    - name: Add Public Key
      apt_key:
        url: https://apt.puppetlabs.com/keyring.gpg
        state: present
    - name: Install Puppet Repo
      apt_repository:
        repo: deb https://apt.puppetlabs.com/ {{ ansible_distribution_release }} {{ puppet_version }}
        state: present
        filename: /etc/apt/sources.list.d/{{ puppet_version }}.list

- name: Install Foreman Repository
  block:
    - name: Add Public Key
      apt_key:
        url: https://deb.theforeman.org/foreman.asc
        state: present
    - name: Install Foreman Repo
      apt_repository:
        repo: deb https://deb.theforeman.org/ {{ ansible_distribution_release }} {{ foreman_version }}
        state: present
        filename: /etc/apt/sources.list.d/foreman.list
    - name: Install Foreman Plugin Repo
      apt_repository:
        repo: deb https://deb.theforeman.org/ plugins {{ foreman_version }}
        state: present
        filename: /etc/apt/sources.list.d/foreman_plugins.list

- name: "Install Git"
  ansible.builtin.apt: 
    name: git 
    force: yes 
    allow_unauthenticated: true

- name: "Download Foreman installer package"
  ansible.builtin.apt:
    name: foreman-installer
    force: yes
    allow_unauthenticated: true

- name: "Install Puppet Agent"
  ansible.builtin.apt: 
    name: puppet-agent 
    force: yes 
    allow_unauthenticated: true
    
- name: "Bootstap Puppet Agent ssl"
  ansible.builtin.shell: |
    /opt/puppetlabs/bin/puppet config set server {{ groups['tfm_puppet'][0] }} --section main
    /opt/puppetlabs/bin/puppet ssl bootstrap --server {{ groups['tfm_puppet'][0] }}

- name: "Install and Configure Puppet Root CA"
  block:
    - name: "Fetch Puppet Root CA"
      ansible.builtin.shell: |
        echo quit | openssl s_client -showcerts -servername server -connect {{ groups['tfm_puppet'][0] }}:8140 > /usr/local/share/ca-certificates/{{ groups['tfm_puppet'][0] }}-CA.crt 2>&1
      args:
        executable: /bin/bash  
    - name: "Install Puppet Root CA"
      ansible.builtin.shell: |
        update-ca-certificates --fresh
      args:
        executable: /bin/bash  

- name: Ensure group "puppet" exists
  ansible.builtin.group:
    name: puppet
    state: present

- name: Ensure group "foreman-proxy" exists
  ansible.builtin.group:
    name: foreman-proxy
    state: present

- name: Creates directory /etc/bind
  ansible.builtin.file:
    path: /etc/bind
    state: directory
    owner: root
    group: foreman-proxy
    mode: 0750

- name: Creating file /etc/bind/rndc.key
  ansible.builtin.copy:
    dest: /etc/bind/rndc.key
    content: |
      key "foreman" {
              algorithm hmac-md5;
              secret "tUJGI0Gd5xJokIvxqpo2oA==";
      };
    owner: root
    group: foreman-proxy
    mode: 0640

- name: "Install and Configure Foreman PROXY"
  block:
    - name: "Install Foreman PROXY"
      vars:
        argv_start:
        - foreman-installer
        - --no-enable-foreman
        - --no-enable-puppet
        - --no-enable-foreman-plugin-puppet 
        - --no-enable-foreman-cli-puppet
        - --enable-foreman-proxy
        - --puppet-group=root
        - --puppet-codedir="/etc/puppetlabs/code"
      ansible.builtin.shell: |
        {{ argv_start | join(' ') }} \
        {{ foreman_cmd_options | join(' ') }}
      args:
        executable: /bin/bash

    - name: Creating file /etc/puppetlabs/puppet/autosign.conf
      ansible.builtin.copy:
        dest: /etc/puppetlabs/puppet/autosign.conf
        content: |
          *.opn.lab
        owner: root
        group: foreman-proxy
        mode: 0664

    - name: SALT test, Creating file /etc/salt/autosign.conf
      ansible.builtin.copy:
        dest: /etc/salt/autosign.conf
        content: |
          *.opn.lab
        owner: foreman-proxy
        group: root
        mode: 0600
      when: _salt_test | bool

    - name: SALT test, Creating file /etc/salt/foreman.yaml
      ansible.builtin.copy:
        dest: /etc/salt/foreman.yaml
        content: |
          ---
          :proto: https
          :host: {{ groups['tfm_app'][0] }}
          :port: 443
          :ssl_ca: "/etc/puppetlabs/puppet/ssl/certs/ca.pem"
          :ssl_cert: "/etc/puppetlabs/puppet/ssl/certs/tfm-proxy-salt.opn.lab.pem"
          :ssl_key: "/etc/puppetlabs/puppet/ssl/private_keys/tfm-proxy-salt.opn.lab.pem"
          :timeout: 10
          :salt: /usr/bin/salt
          :upload_grains: true
        owner: root
        group: root
        mode: 0644
      when: _salt_test | bool

    - name: SALT test, bootstrap local salt-master & salt-api
      ansible.builtin.shell: |
        apt-get -qy install salt-master salt-api
        sed -i 's/User=salt/User=root/' /lib/systemd/system/salt-master.service
        sed -i 's/Group=salt/Group=root/' /lib/systemd/system/salt-master.service
        # sed -i 's/# permissive_pki_access: True/permissive_pki_access: True/' /etc/salt/master.d/foreman.conf
        systemctl daemon-reload
        systemctl restart salt-master.service salt-api.service
        adduser --no-create-home --disabled-password --gecos '' --shell /bin/false --home / saltuser
        echo "saltuser:saltpassword" | chpasswd
        touch /etc/salt/autosign.conf
        chgrp foreman-proxy /etc/salt/autosign.conf
        chmod 660 /etc/salt/autosign.conf
        mkdir -p /usr/share/foreman-proxy/salt/reactors
        mkdir -p /var/lib/foreman-proxy/salt/grains
        mkdir -p /srv/pillar
        mkdir -p /srv/salt
        git clone https://github.com/SS-archive/salt-states.git /srv/salt
        mkdir -p /srv/salt/_runners
        git clone https://github.com/theforeman/smart_proxy_salt.git /usr/src/smart_proxy_salt
        cp /usr/src/smart_proxy_salt/salt/minion_auth/foreman_minion_auth.sls /usr/share/foreman-proxy/salt/reactors/
        cp /usr/src/smart_proxy_salt/salt/minion_auth/srv/salt/_runners/foreman_file.py /srv/salt/_runners/
        cp /usr/src/smart_proxy_salt/salt/minion_auth/srv/salt/_runners/foreman_https.py /srv/salt/_runners/
        cp /usr/src/smart_proxy_salt/salt/report_upload/foreman_report_upload.sls /usr/share/foreman-proxy/salt/reactors/
        cp /usr/src/smart_proxy_salt/salt/report_upload/srv/salt/_runners/foreman_report_upload.py /srv/salt/_runners/
        usermod -a -G foreman-proxy root
        systemctl restart salt-master salt-api
        sleep 10
        salt-run saltutil.sync_all
      when: _salt_test | bool

    - name: Add contents to sudoers
      lineinfile:
        path: /etc/sudoers
        line: |
          Cmnd_Alias SALT = /usr/bin/salt, /usr/bin/salt-key
          foreman-proxy ALL = (ALL) NOPASSWD: SALT
          Defaults:foreman-proxy !requiretty
      when: _salt_test | bool

    - name: Restart service foreman-proxy
      ansible.builtin.service:
        name: foreman-proxy
        state: restarted

- name: Creates directory /etc/ansible
  ansible.builtin.file:
    path: /etc/ansible
    state: directory
    owner: root
    group: foreman-proxy
    mode: 0750

- name: Creating empty file /etc/ansible/ansible.cfg
  ansible.builtin.copy:
    dest: /etc/ansible/ansible.cfg
    content: ""
    owner: root
    group: foreman-proxy
    mode: 0640

- name: "Bootstap Puppet Agent ssl"
  ansible.builtin.shell: |
    /opt/puppetlabs/bin/puppet config set server {{ groups['tfm_puppet'][0] }} --section main

- name: Restart service puppet
  ansible.builtin.service:
    name: puppet
    state: restarted
